-- Base de Datos exportada automáticamente a través de la herramienta en MySQL Workbench

-- MySQL Script generated by MySQL Workbench
-- MySQL dump 10.13  Distrib 8.0.40, for Win64 (x86_64)
--
-- Host: localhost    Database: ozel
-- ------------------------------------------------------
-- Server version	8.0.40

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `carrito`
--

DROP TABLE IF EXISTS `carrito`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `carrito` (
  `CartID` int NOT NULL AUTO_INCREMENT,
  `Quantity` int NOT NULL,
  `Productos_ProductID` int NOT NULL,
  `Usuarios_AccountID` int NOT NULL,
  PRIMARY KEY (`CartID`,`Productos_ProductID`,`Usuarios_AccountID`),
  KEY `fk_Carrito_Productos1_idx` (`Productos_ProductID`),
  KEY `fk_Carrito_Usuarios1_idx` (`Usuarios_AccountID`),
  CONSTRAINT `fk_Carrito_Productos1` FOREIGN KEY (`Productos_ProductID`) REFERENCES `productos` (`ProductID`),
  CONSTRAINT `fk_Carrito_Usuarios1` FOREIGN KEY (`Usuarios_AccountID`) REFERENCES `usuarios` (`AccountID`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `carrito`
--

LOCK TABLES `carrito` WRITE;
/*!40000 ALTER TABLE `carrito` DISABLE KEYS */;
INSERT INTO `carrito` VALUES (9,1,1,7),(10,1,2,8);
/*!40000 ALTER TABLE `carrito` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `categorias`
--

DROP TABLE IF EXISTS `categorias`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `categorias` (
  `id` int NOT NULL AUTO_INCREMENT,
  `categoria` varchar(255) NOT NULL,
  `subcategoria` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `categorias`
--

LOCK TABLES `categorias` WRITE;
/*!40000 ALTER TABLE `categorias` DISABLE KEYS */;
INSERT INTO `categorias` VALUES (1,'Inferior','Pollera'),(2,'Top','Fiesta');
/*!40000 ALTER TABLE `categorias` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `colores`
--

DROP TABLE IF EXISTS `colores`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `colores` (
  `idColor` int NOT NULL AUTO_INCREMENT,
  `color` varchar(255) NOT NULL,
  PRIMARY KEY (`idColor`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `colores`
--

LOCK TABLES `colores` WRITE;
/*!40000 ALTER TABLE `colores` DISABLE KEYS */;
INSERT INTO `colores` VALUES (1,'Verde'),(2,'Negro'),(3,'Bordó');
/*!40000 ALTER TABLE `colores` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `detallespedido`
--

DROP TABLE IF EXISTS `detallespedido`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `detallespedido` (
  `OrderDetailID` int NOT NULL AUTO_INCREMENT,
  `Quantity` int NOT NULL,
  `UnitPrice` decimal(10,2) NOT NULL,
  `Pedidos_OrderID` int NOT NULL,
  `Productos_ProductID` int NOT NULL,
  PRIMARY KEY (`OrderDetailID`,`Pedidos_OrderID`,`Productos_ProductID`),
  KEY `fk_DetallesPedido_Pedidos1_idx` (`Pedidos_OrderID`),
  KEY `fk_DetallesPedido_Productos1_idx` (`Productos_ProductID`),
  CONSTRAINT `fk_DetallesPedido_Pedidos1` FOREIGN KEY (`Pedidos_OrderID`) REFERENCES `pedidos` (`OrderID`),
  CONSTRAINT `fk_DetallesPedido_Productos1` FOREIGN KEY (`Productos_ProductID`) REFERENCES `productos` (`ProductID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `detallespedido`
--

LOCK TABLES `detallespedido` WRITE;
/*!40000 ALTER TABLE `detallespedido` DISABLE KEYS */;
/*!40000 ALTER TABLE `detallespedido` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `envios`
--

DROP TABLE IF EXISTS `envios`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `envios` (
  `ShipmentID` int NOT NULL AUTO_INCREMENT,
  `ShipmentDate` date NOT NULL,
  `Carrier` varchar(45) NOT NULL,
  `TrackingNumber` varchar(45) NOT NULL,
  `Pagos_PaymentID` int NOT NULL,
  PRIMARY KEY (`ShipmentID`,`Pagos_PaymentID`),
  KEY `fk_Envios_Pagos1_idx` (`Pagos_PaymentID`),
  CONSTRAINT `fk_Envios_Pagos1` FOREIGN KEY (`Pagos_PaymentID`) REFERENCES `pagos` (`PaymentID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `envios`
--

LOCK TABLES `envios` WRITE;
/*!40000 ALTER TABLE `envios` DISABLE KEYS */;
/*!40000 ALTER TABLE `envios` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `pagos`
--

DROP TABLE IF EXISTS `pagos`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `pagos` (
  `PaymentID` int NOT NULL AUTO_INCREMENT,
  `PaymentDate` date NOT NULL,
  `Amount` decimal(20,2) NOT NULL,
  `PaymentMethod` varchar(45) NOT NULL,
  `Status` varchar(45) NOT NULL,
  `Pedidos_OrderID` int NOT NULL,
  PRIMARY KEY (`PaymentID`,`Pedidos_OrderID`),
  KEY `fk_Pagos_Pedidos1_idx` (`Pedidos_OrderID`),
  CONSTRAINT `fk_Pagos_Pedidos1` FOREIGN KEY (`Pedidos_OrderID`) REFERENCES `pedidos` (`OrderID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `pagos`
--

LOCK TABLES `pagos` WRITE;
/*!40000 ALTER TABLE `pagos` DISABLE KEYS */;
/*!40000 ALTER TABLE `pagos` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `pedidos`
--

DROP TABLE IF EXISTS `pedidos`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `pedidos` (
  `OrderID` int NOT NULL AUTO_INCREMENT,
  `OrderDate` date NOT NULL,
  `TotalAmount` decimal(10,2) NOT NULL,
  `Status` varchar(45) NOT NULL,
  `Usuarios_AccountID` int NOT NULL,
  `Address` varchar(100) DEFAULT NULL,
  `City` varchar(45) DEFAULT NULL,
  `Provincia` varchar(45) DEFAULT NULL,
  `PostalCode` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`OrderID`,`Usuarios_AccountID`),
  KEY `fk_Pedidos_Usuarios_idx` (`Usuarios_AccountID`),
  CONSTRAINT `fk_Pedidos_Usuarios` FOREIGN KEY (`Usuarios_AccountID`) REFERENCES `usuarios` (`AccountID`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `pedidos`
--

LOCK TABLES `pedidos` WRITE;
/*!40000 ALTER TABLE `pedidos` DISABLE KEYS */;
INSERT INTO `pedidos` VALUES (1,'2024-11-16',55000.00,'Procesando',1,'as4','alta gracia','cordoba','5186'),(2,'2024-11-22',9.00,'Pendiente',1,NULL,NULL,'',NULL),(3,'2024-11-22',9.00,'Pendiente',1,NULL,NULL,'',NULL),(4,'2024-11-22',55009.00,'Pendiente',1,NULL,NULL,'',NULL),(5,'2024-11-25',9.00,'Pendiente',3,NULL,NULL,'',NULL),(6,'2024-12-03',55000.00,'Pendiente',1,'ass','alta gracia','cordoba','5186'),(7,'2024-12-12',55000.00,'Cancelado',1,'ass','alta gracia','cordoba','5186'),(8,'2024-12-12',55000.00,'Cancelado',1,'ass','alta gracia','cordoba','5186'),(9,'2024-12-12',110000.00,'Cancelado',1,'ass','alta gracia','cordoba','5186'),(10,'2024-12-12',123200.00,'Cancelado',1,'ass','alta gracia','cordoba','5186'),(11,'2024-12-12',55000.00,'Pendiente',1,'ass','alta gracia','cordoba','5186'),(12,'2024-12-12',55000.00,'Pendiente',1,'ass','alta gracia','cordoba','5186'),(13,'2024-12-12',165000.00,'Pendiente',1,'ass','alta gracia','cordoba','5186'),(14,'2024-12-12',55000.00,'Pendiente',1,'ass','alta gracia','cordoba','5186');
/*!40000 ALTER TABLE `pedidos` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `pedidosproductos`
--

DROP TABLE IF EXISTS `pedidosproductos`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `pedidosproductos` (
  `OrderID` int NOT NULL,
  `Productos_ProductID` int NOT NULL,
  `Quantity` int NOT NULL,
  `Price` decimal(10,2) NOT NULL,
  PRIMARY KEY (`OrderID`,`Productos_ProductID`),
  KEY `Productos_ProductID` (`Productos_ProductID`),
  CONSTRAINT `pedidosproductos_ibfk_1` FOREIGN KEY (`OrderID`) REFERENCES `pedidos` (`OrderID`),
  CONSTRAINT `pedidosproductos_ibfk_2` FOREIGN KEY (`Productos_ProductID`) REFERENCES `productos` (`ProductID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `pedidosproductos`
--

LOCK TABLES `pedidosproductos` WRITE;
/*!40000 ALTER TABLE `pedidosproductos` DISABLE KEYS */;
INSERT INTO `pedidosproductos` VALUES (1,2,1,55000.00),(2,5,1,10.00),(3,5,1,9.00),(4,2,1,55000.00),(4,5,1,9.00),(5,5,1,9.00),(6,2,1,55000.00),(7,2,1,55000.00),(8,2,1,55000.00),(9,2,2,55000.00),(10,1,1,13200.00),(10,2,2,55000.00),(11,2,1,55000.00),(12,2,1,55000.00),(13,2,3,55000.00),(14,2,1,55000.00);
/*!40000 ALTER TABLE `pedidosproductos` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `productos`
--

DROP TABLE IF EXISTS `productos`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `productos` (
  `ProductID` int NOT NULL AUTO_INCREMENT,
  `Category` varchar(45) NOT NULL,
  `Subcategory` varchar(45) DEFAULT NULL,
  `ProductName` varchar(45) NOT NULL,
  `Description` varchar(45) DEFAULT NULL,
  `Price` decimal(10,2) NOT NULL,
  `Stock` int DEFAULT NULL,
  `ImageURL` varchar(90) DEFAULT NULL,
  `DateAdded` date DEFAULT NULL,
  `Size` varchar(45) NOT NULL,
  `Color` varchar(45) NOT NULL,
  `Productoscol` varchar(45) DEFAULT NULL,
  `Discount` decimal(10,2) DEFAULT '0.00',
  `SaleStart` date DEFAULT NULL,
  `SaleEnd` date DEFAULT NULL,
  `IsHidden` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`ProductID`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `productos`
--

LOCK TABLES `productos` WRITE;
/*!40000 ALTER TABLE `productos` DISABLE KEYS */;
INSERT INTO `productos` VALUES (1,'Inferior','Pollera','Pollera verde','pollera verde ankara',33000.00,11,'/uploads/1733752090903-Pollera KONYA verde.jpg','2024-11-05','M','Verde',NULL,60.00,'2024-11-03','2024-11-03',0),(2,'Top','Fiesta','top negro','Top negro RIZE',55000.00,19,'/uploads/1733752080367-Top RIZE negro.jpg','2024-11-05','M','Negro',NULL,0.00,'2024-11-04','2024-11-04',0),(5,'Inferior','Pollera','test','asd',10.00,2,'/uploads/1732111189569-Top RIZE negro.jpg','2024-11-14','M','Negro',NULL,1.00,NULL,NULL,1),(9,'Inferior','Pollera','Pollera bordó','Pollera HOPA',65000.00,4,'/uploads/1733752432911-Pollera HOPA bordÃ³.png','2024-12-09','M','Bordó',NULL,20.00,NULL,NULL,0);
/*!40000 ALTER TABLE `productos` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `tallas`
--

DROP TABLE IF EXISTS `tallas`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tallas` (
  `idTalla` int NOT NULL AUTO_INCREMENT,
  `talla` varchar(255) NOT NULL,
  PRIMARY KEY (`idTalla`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `tallas`
--

LOCK TABLES `tallas` WRITE;
/*!40000 ALTER TABLE `tallas` DISABLE KEYS */;
INSERT INTO `tallas` VALUES (1,'M');
/*!40000 ALTER TABLE `tallas` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `usuarios`
--

DROP TABLE IF EXISTS `usuarios`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `usuarios` (
  `AccountID` int NOT NULL AUTO_INCREMENT,
  `FirstName` varchar(45) NOT NULL,
  `LastName` varchar(45) NOT NULL,
  `Email` varchar(60) NOT NULL,
  `Password` varchar(60) NOT NULL,
  `Phone` varchar(60) DEFAULT NULL,
  `Address` varchar(45) DEFAULT NULL,
  `City` varchar(45) DEFAULT NULL,
  `PostalCode` varchar(45) DEFAULT NULL,
  `DateRegistered` date DEFAULT NULL,
  `Role` varchar(45) NOT NULL DEFAULT 'client',
  `Provincia` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`AccountID`),
  UNIQUE KEY `Email_UNIQUE` (`Email`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `usuarios`
--

LOCK TABLES `usuarios` WRITE;
/*!40000 ALTER TABLE `usuarios` DISABLE KEYS */;
INSERT INTO `usuarios` VALUES (1,'admin','admin','admin@admin','$2b$10$Q4wFA8jqiclpAmu.4Zh9iuby05eaQj1v.bEMvkr9HokTgbpZYj4Mq','123','ass','alta gracia','5186','2024-10-30','admin','cordoba'),(2,'valentin','filoniuk','vfiloniuk058@alumnos.iua.edu.ar','$2b$10$PQkOE16AvQU0dgl.KdsISe1JyUNugbdxT/GsshFyvYe5tViwu0LgW',NULL,NULL,NULL,NULL,'2024-11-19','gestor',NULL),(3,'valen','prueba','valenprueba@gmail.com','$2b$10$z8m5twHEEHRaC3ewkpF6juaVxJXmdfoOKrmf5ZWl.zO9CMqUXFpOW',NULL,NULL,NULL,NULL,'2024-11-25','client',NULL),(4,'valen','prueba','valen@valen','$2b$10$KO9MbpQ92qIBigYdwwzJp.ukXcrF6fzejJoOgIi07h3EgAZo9wMle','12345','as','alta gracia','5186','2024-11-27','client','cordoba'),(5,'valenprueba','probando','valen@gmail.com','$2b$10$oy7r8Bfu7gQMQWq36lnpeupRwf9S7Umc781ISP8wZgAIC9uGqV/by','1234','asiii','alta gracia','5186','2024-11-27','client','cordobas'),(6,'asd','sadas','asd@asd','$2b$10$OyNVr4NFuqURbUd27m9ijeqp1nnB/4aGwBDWVAINd7di6VgNT3XZ.','1234','asd','asd','asd','2024-11-27','client','asd'),(7,'preuab','prueba','prueba@prueba','$2b$10$6eKkMKqr/OEt4EmT5/wnU.IE23kvzpT6TX3zjhiuc1clDnVMG1tt2','1','asd','asd','123','2024-11-29','client','asd'),(8,'prueba','2023','prueba2@prueba2','$2b$10$hvqvxG/A0PMryx6iW1YrpuyOj3krODScA0kSYmaD2089ro5/.Pv6y',NULL,NULL,NULL,NULL,'2024-11-29','client',NULL),(9,'preuba','nuevo','nuevo@nuevo','$2b$10$HyuhG.g/DPGRhTrdAUs3h.gIFkYUWVLr7J99PkMPmJJAS2xQjfUxC',NULL,NULL,NULL,NULL,'2024-12-03','client',NULL);
/*!40000 ALTER TABLE `usuarios` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2024-12-13 10:16:59
